# Generated by Django 2.0.13 on 2021-06-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuristicPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('resources', models.ManyToManyField(to='resources.Resource')),
            ],
        ),
    ]
