# Generated by Django 2.0.13 on 2021-06-26 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('core', '0003_turisticpoint_avaliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='addresses.Address'),
            preserve_default=False,
        ),
    ]
