# Generated by Django 2.0.13 on 2021-06-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_turisticpoint_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='turisticpoint',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='turistic_points'),
        ),
    ]
