# Generated by Django 2.0.13 on 2021-06-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_turisticpoint_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turisticpoint',
            old_name='foto',
            new_name='photo',
        ),
    ]
